client-app/uncommon-sync/salesdoc-sync/quote-sync/objects/OBJ_Quote__c/OBJ_Quote__c.object-meta.xml
<CustomObject>
    <label>OBJ Quote</label>
    <nameField>
        <label>OBJ SAP Quote</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OBJ SAP Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

client-app/uncommon-sync/salesdoc-sync/quote-sync/objects/OBJ_Quote_Item__c/OBJ_Quote_Item__c.object-meta.xml
<CustomObject>
    <label>OBJ Quote Item</label>
    <nameField>
        <label>OBJ SAP Quote Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OBJ SAP Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

client-app/uncommon-sync/salesdoc-sync/quote-sync/objects/OBJ_Quote_Item__c/fields/FLD_OBJ_Quote__c.field-meta.xml
<CustomField>
    <fullName>FLD_OBJ_Quote__c</fullName>
    <description>OBJ Quote</description>
    <inlineHelpText>OBJ Quote</inlineHelpText>
    <label>FLD OBJ Quote</label>
    <referenceTo>OBJ_Quote__c</referenceTo>
    <relationshipLabel>OBJ Quote Item (OBJ Quote)</relationshipLabel>
    <relationshipName>OBJ_Quote_Item_OBJ_Quote</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

client-app/uncommon-sync/salesdoc-sync/quote-sync/classes/UTIL_QuoteSyncBatch.cls
public with sharing class UTIL_QuoteSyncBatch
    extends UTIL_SalesDocSyncBatch
    implements Database.Batchable<Object>,
    Database.AllowsCallouts,
    Database.Stateful,
    I_ParameterizedSync
{
    private Static String transactionGroup = '2';
    private Static String batchClassName = 'UTIL_QuoteSyncBatch';
    private Static String scheduleClassName = 'UTIL_QuoteSyncSchedule';

    public UTIL_QuoteSyncBatch()
    {
        super(transactionGroup, 'OBJ_Quote__c', 'OBJ_Quote_Item__c', 'FLD_OBJ_Quote__c', 'FLD_OBJ_Quote__r', scheduleClassName, batchClassName);
    }

    /* Database.Batchable methods start(), execute(), and finish() */
    // start()
    public List<Object> start(Database.BatchableContext context)
    {
        return super.startBatch(context);
    }

    // execute()
    public void execute(
        Database.BatchableContext context,
        List<Object> searchResults)
    {
        super.executeBatch(context, searchResults);
    }

    // finish()
    public void finish(Database.BatchableContext context)
    {
        super.finishBatch(context);
    }

    public static Integer getTotalRecordCount () 
    {
        return UTIL_SalesDocSyncBatch.getRecordCount(true, transactionGroup, scheduleClassName, batchClassName);
    }

    public static Integer getNextIncrementalRecordCount () 
    {
        return UTIL_SalesDocSyncBatch.getRecordCount(false, transactionGroup, scheduleClassName, batchClassName);
    }
}