defunct/client-app/base-sobjects/objects/Contact.object
<CustomObject>
</CustomObject>

client-app/common-sync/customer-sync/objects/Contact/fields/FLD_ContactPersonNumber__c.field-meta.xml
<CustomField>
    <fullName>FLD_ContactPersonNumber__c</fullName>
    <label>FLD Contact Person Number</label>
    <description>Contact Person Number</description>
    <length>10</length>
    <type>Text</type>
</CustomField>

client-app/common-sync/customer-sync/objects/Contact/fields/FLD_CustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>FLD_CustomerNumber__c</fullName>
    <label>FLD Customer Number</label>
    <description>Customer Number Field</description>
    <length>10</length>
    <type>Text</type>
</CustomField>

client-app/common-core/classes/UTIL_SFContact.cls
public with sharing class UTIL_SFContact
{
    private static final ensxsdk.Logger logger = new ensxsdk.Logger(UTIL_SFContact.class);

    // Returns the field name which stores the SAP Contact number
    public static String ContactFieldName
    {
        get
        {
            return (String)UTIL_AppSettings.getValue(UTIL_AppSettings.EnterpriseApp, 'Contact.ContactFieldName', 'FLD_ContactPersonNumber__c');
        }
    }

    // Returns the field name which stores the SAP Customer number
    public static String ContactCustomerFieldName
    {
        get
        {
            return (String)UTIL_AppSettings.getValue(UTIL_AppSettings.EnterpriseApp, 'Contact.ContactCustomerFieldName', 'FLD_CustomerNumber__c');
        }
    }

    // getContactFromId()
    //
    // Get the contact from the given Id
    public static Contact getContactFromId(Id value)
    {
        Contact result = null;

        try
        {
            if (null != value)
            {
                result = Database.query(
                    'SELECT Id, FirstName, LastName, Phone, AccountId, Department, Email, ' + 
                    'Fax, MobilePhone, Title, ' + UTIL_SFContact.ContactFieldName + 
                    ' FROM Contact WHERE Id = \'' + value + '\' LIMIT 1');
            }
        }
        catch (Exception e) {}
        return result;
    }

    public static String getContactNumberFromContact(Contact contact)
    {
        return (String) contact.get(UTIL_SFContact.ContactFieldName);
    }

    public static void setContactContactNumber(Contact contact, string contactNumber)
    {
        contact.put(UTIL_SFContact.ContactFieldName, contactNumber);
    }
}