client-app/uncommon-sync/salesdoc-sync/order-sync/objects/OBJ_Order__c/OBJ_Order__c.object-meta.xml
<CustomObject>
    <label>OBJ Order</label>
    <nameField>
        <label>OBJ SAP Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OBJ SAP Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

client-app/uncommon-sync/salesdoc-sync/order-sync/objects/OBJ_Order_Item__c/OBJ_Order_Item__c.object-meta.xml
<CustomObject>
    <label>OBJ Order Item</label>
    <nameField>
        <label>OBJ SAP Order Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OBJ SAP Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

client-app/uncommon-sync/salesdoc-sync/order-sync/objects/OBJ_Order_Item__c/fields/FLD_OBJ_Order__c.field-meta.xml
<CustomField>
    <fullName>FLD_OBJ_Order__c</fullName>
    <description>OBJ Order</description>
    <inlineHelpText>OBJ Order</inlineHelpText>
    <label>FLD OBJ Order</label>
    <referenceTo>OBJ_Order__c</referenceTo>
    <relationshipLabel>OBJ Order Item (OBJ Order)</relationshipLabel>
    <relationshipName>OBJ_Order_Item_OBJ_Order</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

client-app/uncommon-sync/salesdoc-sync/order-sync/classes/UTIL_OrderSyncBatch.cls
public with sharing class UTIL_OrderSyncBatch
    extends UTIL_SalesDocSyncBatch
    implements Database.Batchable<Object>,
    Database.AllowsCallouts,
    Database.Stateful,
    I_ParameterizedSync
{
    private Static String transactionGroup = '0';
    private Static String batchClassName = 'UTIL_OrderSyncBatch';
    private Static String scheduleClassName = 'UTIL_OrderSyncSchedule';

    public UTIL_OrderSyncBatch()
    {
        super(transactionGroup, 'OBJ_Order__c', 'OBJ_Order_Item__c', 'FLD_OBJ_Order__c', 'FLD_OBJ_Order__r', scheduleClassName, batchClassName);
    }

    /* Database.Batchable methods start(), execute(), and finish() */
    // start()
    public List<Object> start(Database.BatchableContext context)
    {
        return super.startBatch(context);
    }

    // execute()
    public void execute(
        Database.BatchableContext context,
        List<Object> searchResults)
    {
        super.executeBatch(context, searchResults);
    }

    // finish()
    public void finish(Database.BatchableContext context)
    {
        super.finishBatch(context);
    }

    public static Integer getTotalRecordCount () 
    {
        return UTIL_SalesDocSyncBatch.getRecordCount(true, transactionGroup, scheduleClassName, batchClassName);
    }

    public static Integer getNextIncrementalRecordCount () 
    {
        return UTIL_SalesDocSyncBatch.getRecordCount(false, transactionGroup, scheduleClassName, batchClassName);
    }
}